backend:
  name: github
  repo: renovacionlosandes/renovacion1-12
  branch: main
  auth_type: implicit
  app_id: Ov23liJwcsM3nMKeXPLk
  
media_folder: "imagenes" # Carpeta donde se guardarán las imágenes
public_folder: "/imagenes"

collections:
  - name: "paginas"
    label: "Páginas"
    files:
      - label: "Inicio"
        name: "inicio"
        file: "content/inicio.yml"
        fields:
          - { label: "Título de página", name: "title", widget: "string" }

          - label: "Banner"
            name: "banner"
            widget: "list"
            fields: 
               - { label: "Imagen", name: "imagen", widget: "image" }

          - { label: "Logo", name: "logo", widget: "image" }

          - label: "Bienvenida"
            name: "bienvenida"
            widget: "object"
            fields:
              - { label: "Titulo", name: "titulo", widget: "string" }
              - { label: "Texto", name: "texto", widget: "markdown" }
              - { label: "Imagen", name: "imagen", widget: "image" }

          - label: "Secciones"
            name: "secciones"
            widget: "list"
            fields:
              - { label: "Tipo", name: "tipo", widget: "string"}
              - { label: "Título", name: "titulo", widget: "string" }
              - { label: "Contenido", name: "contenido", widget: "markdown" }





















